// Excel のセルに入りがちな業務文書の日本語（ルール比較用）
// kind: "sentence" は文章のセル、"short" は見出し・単語・値だけのセル（誤検出の確認用）
export const CORPUS = [
  // 文章のセル（違反を含む）
  { id: "S01", kind: "sentence", text: "サーバーを再起動して下さい。", note: "補助動詞の「下さい」" },
  { id: "S02", kind: "sentence", text: "１２３件のデータがあります。", note: "全角数字" },
  { id: "S03", kind: "sentence", text: "データを取得することができる。", note: "冗長な表現" },
  { id: "S04", kind: "sentence", text: "出来る限り早く対応致します。", note: "「出来る」「致します」" },
  { id: "S05", kind: "sentence", text: "内容を確認の上、ご連絡させて頂きます。", note: "補助動詞の「頂く」" },
  { id: "S06", kind: "sentence", text: "この画面からは設定が見れない。", note: "ら抜き" },
  { id: "S07", kind: "sentence", text: "先方に確認し、その上で、担当者と相談し、改めて、ご連絡します。", note: "読点が多い" },
  { id: "S08", kind: "sentence", text: "材料不足で代替素材で製品を作った。", note: "助詞の連続" },
  { id: "S09", kind: "sentence", text: "資料を作成した。明日提出します。", note: "である調とですます調の混在" },
  { id: "S10", kind: "sentence", text: "この方法で問題ないと思われます。", note: "弱い表現" },
  { id: "S11", kind: "sentence", text: "ユーザー登録が完了しました!", note: "半角の感嘆符" },
  { id: "S12", kind: "sentence", text: "見積書(案)を添付します。", note: "半角の丸かっこ" },
  { id: "S13", kind: "sentence", text: "Excelファイルを共有フォルダに保存してください。", note: "半角英字と全角の間（スペースなし）" },
  { id: "S14", kind: "sentence", text: "Excel ファイルを共有フォルダに保存してください。", note: "半角英字と全角の間（スペースあり）" },
  { id: "S15", kind: "sentence", text: "ＡＢＣ社のＷｅｂサイトを更新します。", note: "全角英字" },
  { id: "S16", kind: "sentence", text: "今期の売上は前年比１１０％です。", note: "全角数字と全角％" },
  { id: "S17", kind: "sentence", text: "但し、例外として事前申請が必要な場合もある。", note: "「但し」" },
  { id: "S18", kind: "sentence", text: "〇〇について検討を行う事とする。", note: "形式名詞の「事」" },
  { id: "S19", kind: "sentence", text: "宜しくお願い致します。", note: "「宜しく」「致します」" },
  { id: "S20", kind: "sentence", text: "ｻｰﾊﾞｰの設定を変更しました。", note: "半角カナ" },
  { id: "S21", kind: "sentence", text: "サーバの設定とサーバーの設定を比較する。", note: "表記ゆれ（長音）" },
  { id: "S22", kind: "sentence", text: "javascriptとGithubを使って開発する。", note: "技術用語の表記" },
  { id: "S23", kind: "sentence", text: "問題が無いわけではない。", note: "二重否定" },
  { id: "S24", kind: "sentence", text: "この件はこれは問題ありません", note: "句点なしの文" },
  { id: "S25", kind: "sentence", text: "詳細は、以下の手順を参照してください。、", note: "句読点の連続" },
  { id: "S26", kind: "sentence", text: "1行目の説明です\n2行目の説明です", note: "セル内改行（句点なし）" },
  // 短いセル（見出し・単語・値）
  { id: "H01", kind: "short", text: "売上集計", note: "見出し" },
  { id: "H02", kind: "short", text: "対応済", note: "単語" },
  { id: "H03", kind: "short", text: "1.概要", note: "番号付き見出し" },
  { id: "H04", kind: "short", text: "担当者:山田", note: "半角コロン" },
  { id: "H05", kind: "short", text: "業務効率化推進委員会議事録", note: "漢字の連続（見出し）" },
  { id: "H06", kind: "short", text: "2026/04/01", note: "日付" },
  { id: "H07", kind: "short", text: "¥10,000", note: "金額" },
  { id: "H08", kind: "short", text: "要確認!", note: "短いメモ" },
  { id: "H09", kind: "short", text: "第３四半期", note: "見出し（全角数字）" },
  { id: "H10", kind: "short", text: "〜3月末", note: "期限" },
];
